[nodemanager]
server = https://console.planetlab.io
identity = /etc/edgenet/identity.json
state = /var/lib/edgenet/state.json

[orchestrator]
host = n.planetlab.io

[admin]
user = edgenet
public_key =